name: "Update composer lock file"

on:
  push:
    paths:
      - 'composer.lock'

jobs:
  build:
    name: get the files and update
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          command: update
