name: "Update composer lock file"

on:
  push:
    paths:
      - 'composer.lock'
  workflow_dispatch:

jobs:
  build:
    name: get the files and update
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          command: update
      - name: Commit updated lock file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add composer.lock
          git commit -m "doc: update composer lock file" || exit 0
          git push
